# Generated by Django 3.2.9 on 2022-04-14 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_auto_20220414_0727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('seller_image', models.ImageField(blank=True, null=True, upload_to='chat/')),
                ('buyer_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('buyer_image', models.ImageField(blank=True, null=True, upload_to='chat/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_post', to='products.post')),
            ],
        ),
    ]
