# Generated by Django 3.2.9 on 2022-04-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='buyer_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='buyer_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='seller_image',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='seller_message',
        ),
    ]
