# Generated by Django 3.2.9 on 2022-04-15 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220414_0727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_chatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_chat_group', to='products.post'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='seller_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
