# Generated by Django 3.2.9 on 2022-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20220415_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='seller_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
