# Generated by Django 3.2.9 on 2022-04-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_post_aria_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('moderated', 'Moderated')], max_length=50, null=True),
        ),
    ]
