# Generated by Django 3.2.9 on 2022-03-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='aria_unit',
            field=models.CharField(blank=True, choices=[('kanal', 'Kanal'), ('marla', 'Marla'), ('square_feet', 'Square Feet'), ('square_meter', 'Square Meter'), ('square_yards', 'Square Yards')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='features',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
