# Generated by Django 3.2.9 on 2022-03-31 15:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_post_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True),
        ),
    ]
